// src/components/BookCard.tsx
/**
 * BookCard Component
 *
 * Displays a book in the library with title, author, and narration status.
 * Status indicators per ARCHITECTURE.md:
 *   - text-only = no narration yet
 *   - processing = narration being generated
 *   - ready = narration complete, can play
 *
 * Uses GLOSSARY.md terminology: "narration" not "audio"
 */

import { useState, useRef, useEffect, useCallback } from 'react';
import type { Book } from '../types';

// =============================================================================
// Props Interface
// =============================================================================

export interface BookCardProps {
  /** The book to display */
  book: Book;
  /** Callback when the card is clicked (opens the book in reader) */
  onClick: () => void;
  /** Callback to generate narration for this book */
  onGenerateNarration?: () => void;
  /** Callback to delete this book from the library */
  onDelete?: () => void;
}

// =============================================================================
// Styles
// =============================================================================

const styles = {
  card: {
    display: 'flex',
    flexDirection: 'column' as const,
    padding: '16px',
    borderRadius: '12px',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    cursor: 'pointer',
    transition: 'box-shadow 0.2s ease, transform 0.2s ease, border-color 0.2s ease',
    minHeight: '140px',
    position: 'relative' as const,
  },
  cardHover: {
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    transform: 'translateY(-2px)',
    borderColor: 'var(--text-accent)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  statusIcon: {
    fontSize: '24px',
    marginBottom: '8px',
  },
  kebabButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    borderRadius: '4px',
    color: 'var(--text-secondary)',
    fontSize: '16px',
    lineHeight: 1,
    transition: 'background-color 0.2s, color 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '-4px',
    marginRight: '-4px',
  },
  kebabButtonHover: {
    backgroundColor: 'var(--bg-primary)',
    color: 'var(--text-primary)',
  },
  menu: {
    position: 'absolute' as const,
    top: '40px',
    right: '8px',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.15)',
    zIndex: 100,
    minWidth: '160px',
    overflow: 'hidden',
  },
  menuItem: {
    display: 'block',
    width: '100%',
    padding: '10px 14px',
    border: 'none',
    background: 'none',
    textAlign: 'left' as const,
    fontSize: '14px',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    transition: 'background-color 0.15s',
  },
  menuItemHover: {
    backgroundColor: 'var(--bg-primary)',
  },
  menuItemDisabled: {
    color: 'var(--text-secondary)',
    cursor: 'not-allowed',
    opacity: 0.6,
  },
  menuItemDanger: {
    color: '#dc2626',
  },
  title: {
    margin: 0,
    fontSize: '15px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
    lineHeight: 1.3,
  },
  author: {
    margin: '6px 0 0 0',
    fontSize: '13px',
    color: 'var(--text-secondary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  footer: {
    marginTop: 'auto',
    paddingTop: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusText: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
  },
  format: {
    fontSize: '11px',
    fontWeight: 500,
    textTransform: 'uppercase' as const,
    color: 'var(--text-secondary)',
    backgroundColor: 'var(--bg-primary)',
    padding: '2px 6px',
    borderRadius: '4px',
  },
};

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Get the status indicator based on narration status
 * Per ARCHITECTURE.md Data Flow section
 */
function getStatusIndicator(status: Book['narrationStatus']): {
  icon: string;
  label: string;
} {
  switch (status) {
    case 'ready':
      return {
        icon: '🎧', // ready - narration complete, can play
        label: 'Ready',
      };
    case 'generating':
      return {
        icon: '⏳', // processing - narration being generated
        label: 'Processing',
      };
    case 'none':
    default:
      return {
        icon: '📖', // text-only - no narration yet
        label: 'Text only',
      };
  }
}

// =============================================================================
// Component
// =============================================================================

export function BookCard({ book, onClick, onGenerateNarration, onDelete }: BookCardProps): JSX.Element {
  const status = getStatusIndicator(book.narrationStatus);
  const [menuOpen, setMenuOpen] = useState(false);
  const [kebabHover, setKebabHover] = useState(false);
  const [hoveredItem, setHoveredItem] = useState<string | null>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  const kebabRef = useRef<HTMLButtonElement>(null);

  const isProcessing = book.narrationStatus === 'generating';

  // Close menu when clicking outside
  useEffect(() => {
    if (!menuOpen) return;

    const handleClickOutside = (event: MouseEvent) => {
      if (
        menuRef.current &&
        !menuRef.current.contains(event.target as Node) &&
        kebabRef.current &&
        !kebabRef.current.contains(event.target as Node)
      ) {
        setMenuOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [menuOpen]);

  const handleKebabClick = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    setMenuOpen((prev) => !prev);
  }, []);

  const handleOpen = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    setMenuOpen(false);
    onClick();
  }, [onClick]);

  const handleGenerateNarration = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    if (isProcessing || !onGenerateNarration) return;
    setMenuOpen(false);
    onGenerateNarration();
  }, [isProcessing, onGenerateNarration]);

  const handleDelete = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    if (!onDelete) return;
    setMenuOpen(false);
    onDelete();
  }, [onDelete]);

  return (
    <div
      style={styles.card}
      onClick={onClick}
      onMouseEnter={(e) => {
        Object.assign(e.currentTarget.style, styles.cardHover);
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.boxShadow = '';
        e.currentTarget.style.transform = '';
        e.currentTarget.style.borderColor = '';
      }}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onClick();
        }
      }}
    >
      <div style={styles.header}>
        <div style={styles.statusIcon}>{status.icon}</div>
        <button
          ref={kebabRef}
          style={{
            ...styles.kebabButton,
            ...(kebabHover ? styles.kebabButtonHover : {}),
          }}
          onClick={handleKebabClick}
          onMouseEnter={() => setKebabHover(true)}
          onMouseLeave={() => setKebabHover(false)}
          aria-label="Book options"
          aria-haspopup="menu"
          aria-expanded={menuOpen}
        >
          &#8942;
        </button>
      </div>

      {menuOpen && (
        <div ref={menuRef} style={styles.menu} role="menu">
          <button
            style={{
              ...styles.menuItem,
              ...(hoveredItem === 'open' ? styles.menuItemHover : {}),
            }}
            onClick={handleOpen}
            onMouseEnter={() => setHoveredItem('open')}
            onMouseLeave={() => setHoveredItem(null)}
            role="menuitem"
          >
            Open
          </button>
          <button
            style={{
              ...styles.menuItem,
              ...(hoveredItem === 'narration' && !isProcessing ? styles.menuItemHover : {}),
              ...(isProcessing ? styles.menuItemDisabled : {}),
            }}
            onClick={handleGenerateNarration}
            onMouseEnter={() => setHoveredItem('narration')}
            onMouseLeave={() => setHoveredItem(null)}
            disabled={isProcessing}
            role="menuitem"
            aria-disabled={isProcessing}
          >
            Generate narration
          </button>
          <button
            style={{
              ...styles.menuItem,
              ...styles.menuItemDanger,
              ...(hoveredItem === 'delete' ? styles.menuItemHover : {}),
            }}
            onClick={handleDelete}
            onMouseEnter={() => setHoveredItem('delete')}
            onMouseLeave={() => setHoveredItem(null)}
            role="menuitem"
          >
            Delete
          </button>
        </div>
      )}

      <h3 style={styles.title}>{book.title}</h3>
      {book.author && <p style={styles.author}>{book.author}</p>}
      <div style={styles.footer}>
        <span style={styles.statusText}>{status.label}</span>
        <span style={styles.format}>{book.sourceFormat}</span>
      </div>
    </div>
  );
}

export default BookCard;

// src-solid/components/BookCard.tsx
/**
 * BookCard Component (Solid)
 */

import { createSignal, onCleanup, type JSX } from 'solid-js';
import type { Book } from '../types';

export interface BookCardProps {
  book: Book;
  onClick: () => void;
  onGenerateNarration?: () => void;
  onDelete?: () => void;
}

const styles = {
  card: {
    display: 'flex',
    'flex-direction': 'column',
    padding: '16px',
    'border-radius': '12px',
    'background-color': 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    cursor: 'pointer',
    transition: 'box-shadow 0.2s ease, transform 0.2s ease, border-color 0.2s ease',
    'min-height': '140px',
    position: 'relative',
  } as JSX.CSSProperties,
  header: {
    display: 'flex',
    'justify-content': 'space-between',
    'align-items': 'flex-start',
  } as JSX.CSSProperties,
  statusIcon: {
    'font-size': '24px',
    'margin-bottom': '8px',
  } as JSX.CSSProperties,
  kebabButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    'border-radius': '4px',
    color: 'var(--text-secondary)',
    'font-size': '16px',
    'line-height': '1',
    transition: 'background-color 0.2s, color 0.2s',
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'center',
    'margin-top': '-4px',
    'margin-right': '-4px',
  } as JSX.CSSProperties,
  menu: {
    position: 'absolute',
    top: '40px',
    right: '8px',
    'background-color': 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    'border-radius': '8px',
    'box-shadow': '0 4px 16px rgba(0, 0, 0, 0.15)',
    'z-index': '100',
    'min-width': '160px',
    overflow: 'hidden',
  } as JSX.CSSProperties,
  menuItem: {
    display: 'block',
    width: '100%',
    padding: '10px 14px',
    border: 'none',
    background: 'none',
    'text-align': 'left',
    'font-size': '14px',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    transition: 'background-color 0.15s',
  } as JSX.CSSProperties,
  title: {
    margin: '0',
    'font-size': '15px',
    'font-weight': '600',
    color: 'var(--text-primary)',
    overflow: 'hidden',
    'text-overflow': 'ellipsis',
    display: '-webkit-box',
    '-webkit-line-clamp': '2',
    '-webkit-box-orient': 'vertical',
    'line-height': '1.3',
  } as JSX.CSSProperties,
  author: {
    margin: '6px 0 0 0',
    'font-size': '13px',
    color: 'var(--text-secondary)',
    overflow: 'hidden',
    'text-overflow': 'ellipsis',
    'white-space': 'nowrap',
  } as JSX.CSSProperties,
  footer: {
    'margin-top': 'auto',
    'padding-top': '12px',
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
  } as JSX.CSSProperties,
  statusText: {
    'font-size': '12px',
    color: 'var(--text-secondary)',
  } as JSX.CSSProperties,
  format: {
    'font-size': '11px',
    'font-weight': '500',
    'text-transform': 'uppercase',
    color: 'var(--text-secondary)',
    'background-color': 'var(--bg-primary)',
    padding: '2px 6px',
    'border-radius': '4px',
  } as JSX.CSSProperties,
};

function getStatusIndicator(status: Book['narrationStatus']) {
  switch (status) {
    case 'ready':
      return { icon: '\u{1F3A7}', label: 'Ready' };
    case 'generating':
      return { icon: '\u{23F3}', label: 'Processing' };
    case 'none':
    default:
      return { icon: '\u{1F4D6}', label: 'Text only' };
  }
}

export function BookCard(props: BookCardProps) {
  const [menuOpen, setMenuOpen] = createSignal(false);
  const [kebabHover, setKebabHover] = createSignal(false);
  const [hoveredItem, setHoveredItem] = createSignal<string | null>(null);
  let menuRef: HTMLDivElement | undefined;
  let kebabRef: HTMLButtonElement | undefined;

  const status = () => getStatusIndicator(props.book.narrationStatus);
  const isProcessing = () => props.book.narrationStatus === 'generating';

  const handleClickOutside = (event: MouseEvent) => {
    if (
      menuRef &&
      !menuRef.contains(event.target as Node) &&
      kebabRef &&
      !kebabRef.contains(event.target as Node)
    ) {
      setMenuOpen(false);
    }
  };

  const setupClickOutside = () => {
    if (menuOpen()) {
      document.addEventListener('mousedown', handleClickOutside);
      onCleanup(() => document.removeEventListener('mousedown', handleClickOutside));
    }
  };

  return (
    <div
      style={styles.card}
      onClick={props.onClick}
      onMouseEnter={(e) => {
        e.currentTarget.style.boxShadow = '0 4px 12px rgba(0, 0, 0, 0.1)';
        e.currentTarget.style.transform = 'translateY(-2px)';
        e.currentTarget.style.borderColor = 'var(--text-accent)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.boxShadow = '';
        e.currentTarget.style.transform = '';
        e.currentTarget.style.borderColor = '';
      }}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          props.onClick();
        }
      }}
    >
      <div style={styles.header}>
        <div style={styles.statusIcon}>{status().icon}</div>
        <button
          ref={kebabRef}
          style={{
            ...styles.kebabButton,
            ...(kebabHover() ? { 'background-color': 'var(--bg-primary)', color: 'var(--text-primary)' } : {}),
          }}
          onClick={(e) => {
            e.stopPropagation();
            setMenuOpen((prev) => !prev);
            setupClickOutside();
          }}
          onMouseEnter={() => setKebabHover(true)}
          onMouseLeave={() => setKebabHover(false)}
          aria-label="Book options"
        >
          &#8942;
        </button>
      </div>

      {menuOpen() && (
        <div ref={menuRef} style={styles.menu} role="menu">
          <button
            style={{
              ...styles.menuItem,
              ...(hoveredItem() === 'open' ? { 'background-color': 'var(--bg-primary)' } : {}),
            }}
            onClick={(e) => {
              e.stopPropagation();
              setMenuOpen(false);
              props.onClick();
            }}
            onMouseEnter={() => setHoveredItem('open')}
            onMouseLeave={() => setHoveredItem(null)}
          >
            Open
          </button>
          <button
            style={{
              ...styles.menuItem,
              ...(hoveredItem() === 'narration' && !isProcessing() ? { 'background-color': 'var(--bg-primary)' } : {}),
              ...(isProcessing() ? { color: 'var(--text-secondary)', cursor: 'not-allowed', opacity: '0.6' } : {}),
            }}
            onClick={(e) => {
              e.stopPropagation();
              if (!isProcessing() && props.onGenerateNarration) {
                setMenuOpen(false);
                props.onGenerateNarration();
              }
            }}
            onMouseEnter={() => setHoveredItem('narration')}
            onMouseLeave={() => setHoveredItem(null)}
            disabled={isProcessing()}
          >
            Generate narration
          </button>
          <button
            style={{
              ...styles.menuItem,
              color: '#dc2626',
              ...(hoveredItem() === 'delete' ? { 'background-color': 'var(--bg-primary)' } : {}),
            }}
            onClick={(e) => {
              e.stopPropagation();
              if (props.onDelete) {
                setMenuOpen(false);
                props.onDelete();
              }
            }}
            onMouseEnter={() => setHoveredItem('delete')}
            onMouseLeave={() => setHoveredItem(null)}
          >
            Delete
          </button>
        </div>
      )}

      <h3 style={styles.title}>{props.book.title}</h3>
      {props.book.author && <p style={styles.author}>{props.book.author}</p>}
      <div style={styles.footer}>
        <span style={styles.statusText}>{status().label}</span>
        <span style={styles.format}>{props.book.sourceFormat}</span>
      </div>
    </div>
  );
}

export default BookCard;
